# Prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Reload config
bind r source-file ~/.tmux.conf \; display "Config reloaded"

# Mouse support
set -g mouse on

# True color support (Neovim/LazyVim)
set -g default-terminal "tmux-256color"

set -as terminal-features ",xterm-256color:RGB"

# Better indexing
set -g base-index 1
setw -g pane-base-index 1

# Faster escape time (better Vim experience)
set -sg escape-time 10

# Split panes like Vim
bind | split-window -h
bind - split-window -v

# Keep current directory when splitting
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Vim style pane navigation

# Biase nav
# bind h select-pane -L
# bind j select-pane -D
# bind k select-pane -U
# bind l select-pane -R

# Navigate panes with Ctrl + Arrow keys

bind -n C-Left select-pane -L
bind -n C-Down select-pane -D
bind -n C-Up select-pane -U 
bind -n C-Right select-pane -R

# Resize panes
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Enable focus events (important for Neovim)
set -g focus-events on

# Status bar
set -g status-position bottom

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Session persistence
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Auto restore
set -g @continuum-restore 'on'

# Neovim navigation
set -g @plugin 'christoomey/vim-tmux-navigator'

# Catppuccin theme
set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavor 'mocha'

# Initialize TPM
run '~/.tmux/plugins/tpm/tpm'
